[colors]
background = "#011423"
foreground = "#CBE0F0"

# Selection
# selection-background = ""
# selection-foreground = ""
#
# # Navigation
# tabs-active = ""
# tabs-active-foreground = ""
# tabs-active-highlight = ""
# bar = ""
cursor = "#47FF9C"
# vi-cursor = ""

# Search
search-match-background = "#033259"
search-match-foreground = "#CBE0F0"
# # search-focused-match-background = ""
# # search-focused-match-foreground = ""
#
# # Regular colors
# black = ""
# blue = ""
# cyan = ""
# green = ""
# magenta = ""
# red = ""
# tabs = ""
# white = ""
# yellow = ""
#
# # Dim colors
# dim-black = ""
# dim-blue = ""
# dim-cyan = ""
# dim-foreground = ""
# dim-green = ""
# dim-magenta = ""
# dim-red = ""
# dim-white = ""
# dim-yellow = ""
#
# # Light colors
# light-black = ""
# light-blue = ""
# light-cyan = ""
# light-foreground = ""
# light-green = ""
# light-magenta = ""
# light-red = ""
# light-white = ""
# light-yellow = ""
#
#
